$env:DB_HOST="localhost"
$env:DB_PORT="5432"
$env:DB_NAME="apex"
$env:DB_USER="apex"
$env:DB_PASSWORD="apex_test"
$env:REDIS_HOST="localhost"
$env:REDIS_PORT="6379"
$env:RABBITMQ_HOST="localhost"
$env:RABBITMQ_PORT="5672"
$env:RABBITMQ_USER="guest"
$env:RABBITMQ_PASSWORD="guest"
$env:JWT_SECRET="test-secret-key-that-is-at-least-32-chars-long!!"
$env:FRONTEND_ORIGIN="http://localhost:5173"
Set-Location "D:\Projects\Apex\Backend"
mvn spring-boot:run
