ALTER TABLE users ALTER COLUMN role DROP DEFAULT;
ALTER TABLE memberships ALTER COLUMN role DROP DEFAULT;
ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(20) USING role::TEXT;
ALTER TABLE memberships ALTER COLUMN role TYPE VARCHAR(20) USING role::TEXT;
ALTER TABLE users ALTER COLUMN role SET DEFAULT 'TRADER';
ALTER TABLE memberships ALTER COLUMN role SET DEFAULT 'TRADER';
DROP TYPE IF EXISTS user_role;
